# Generated by Django 2.2.1 on 2019-07-06 03:06

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='faceJav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='title', max_length=50)),
                ('imgUrl', models.CharField(db_column='IMGURL', max_length=500)),
                ('pageUrl', models.CharField(db_column='PAGEURL', max_length=500)),
                ('description', models.CharField(db_column='description', max_length=500)),
                ('updateTime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 't_facejav',
                'ordering': [builtins.id],
            },
        ),
    ]
