# Generated by Django 2.2.1 on 2019-07-06 17:12

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('xFun', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_column='name', max_length=20)),
                ('password', models.CharField(db_column='password', max_length=50)),
            ],
            options={
                'db_table': 't_xfun_user',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='facejav',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelManagers(
            name='facejav',
            managers=[
                ('fjObject', django.db.models.manager.Manager()),
            ],
        ),
    ]
